global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "middleware"
    static_configs:
      - targets: ["middleware:9091"]
    metrics_path: /metrics

  - job_name: "profile-service"
    static_configs:
      - targets: ["profile-service:9092"]
    metrics_path: /metrics

  - job_name: "outbox-relay"
    static_configs:
      - targets: ["outbox-relay:9093"]
    metrics_path: /metrics

  - job_name: "invalidation-worker"
    static_configs:
      - targets: ["invalidation-worker:9094"]
    metrics_path: /metrics
